//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_department
    {
        public tbl_department()
        {
            this.tbl_employee = new HashSet<tbl_employee>();
        }
    
        public int dep_id { get; set; }
        public string dep_name { get; set; }
    
        public virtual ICollection<tbl_employee> tbl_employee { get; set; }
    }
}
